# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build

on:
  push:
    branches: [ "release" ]

jobs:

  # Builfing react
  build-npm:
  
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./web/

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './web/package-lock.json'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test --passWithNoTests

  # Building go code
  build-go:

    needs: build-npm
  
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build
      run: |
        GOOS=linux GOARCH=arm64 go build -v -o cbFiles_linux_arm64 server/main.go
        GOOS=linux GOARCH=amd64 go build -v -o cbFiles_linux_x64 server/main.go
        GOOS=darwin GOARCH=arm64 go build -v -o cbFiles_macOS_arm64 server/main.go
        GOOS=darwin GOARCH=amd64 go build -v -o cbFiles_macOS_x64 server/main.go
        GOOS=windows GOARCH=amd64 go build -v -o cbFiles_windows_arm64 server/main.go
        GOOS=windows GOARCH=arm go build -v -o cbFiles_windows_x64 server/main.go
        

    - name: Test
      run: go test -v server main.go

