# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "release" ]
  pull_request:
    branches: [ "release" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build
      run: |
        GOOS=linux GOARCH=arm64 go build -v -o cbFiles_linux_arm64 server/main.go
        GOOS=linux GOARCH=amd64 go build -v -o cbFiles_linux_x64 server/main.go
        GOOS=darwin GOARCH=arm64 go build -v -o cbFiles_macOS_arm64 server/main.go
        GOOS=darwin GOARCH=amd64 go build -v -o cbFiles_macOS_x64 server/main.go
        GOOS=windows GOARCH=amd64 go build -v -o cbFiles_windows_arm64 server/main.go
        GOOS=windows GOARCH=arm go build -v -o cbFiles_windows_x64 server/main.go
        

    - name: Test
      run: go test -v server main.go
